platform :ios, '7.0'
pod 'AFNetworking',    '~> 2.0.3'
pod 'HexColors',       '~> 2.2.1'
pod 'HTProgressHUD',   '~> 0.1.1'
pod 'TSMessages',      '~> 0.9.4'
pod 'PDKeychainBindingsController', '~> 0.0.1'
pod 'CocoaLumberjack', '~> 1.7.0'
